services:
  mysql:
    image: mysql:8.0
    container_name: products-catalog-api-mysql
    environment:

      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: products_catalog_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:

      - "3306:3306"
    volumes:
      # Scripts de inicializaci√≥n (DDL / seed)
      - ./db/init:/docker-entrypoint-initdb.d
      # Persistencia de datos
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
